### ISSUE TITLE
feat : 사물인식 기능

### ISSUE THREAD

**Issue by Naerumii** [sparta-A5/Django-MachineLearning#4]
- 웹상에서 사용자가 이미지를 업로드하면 해당 이미지의 카테고리를 출력해주는 서비스를 만들어주세요.
- 고양이 사진을 업로드 하면 품종을 인식해서 태그를 달아주는 기능을 구현해주세요.
- 이미지마다 인식한 사물의 정보를 로그에 저장해주세요.

**Comment by choding91** [comment]
현재 재원님과 진행 중입니다.
모델에 학습 시키는 부분에서 개체 수가 너무 많아 Colab의 GPU로도 진행이 너무 더뎌서 개체 수 삭제 후 다시 적용하고 있습니다.

**Comment by choding91** [comment]
개체 수를 줄이면 아무래도 정확도가 떨어지는데 그 문제를 어떻게 해결해야 될지 의논 중입니다.

**Comment by choding91** [comment]
튜터님 말씀으로는 고양이 품종 분류가 대부분 비슷하게 생겨서 구분하려면 많은 데이터가 필요하고 그걸 학습하려면 시간이 오래 걸릴만큼 원래 어려운 주제라고 하십니다😅

**Comment by Naerumii** [comment]
저희가 생각했던 것 보다 어려운 주제였군요..........🤣 도움이 필요하시면 언제든 얘기해주세요!

**Comment by choding91** [comment]
@Naerumii
감사합니다..! 모델은 여러 방면으로 만들어 보고 있는데 이걸 장고에 어떻게 적용시켜야 될지 감이 안잡히네요 :(
YOLO는 단순히 Cat으로만 분류돼서 Tensorflow .h5 모델 커스텀 진행하고 있습니다.

**Comment by chorimgenius** [comment]
저도 도울 수 있는 부분이 있으면 돕겠습니다!! 도움 필요하시면 말씀해 주세요!!

**Comment by choding91** [comment]
@chorimgenius
감사합니다~ 고양이 사진 구분이 어려워서 그런지 데이터셋 바꿔가면서 해도 val_acc 가 너무 낮게 나오네요 ㅠ
일단 재원님이랑 저녁때까지 계속 진행해 보겠습니다..!

**Comment by choding91** [comment]
model.h5 파일은 용량 문제로 push 가 되지 않는 상황입니다.
추후 main 에 PR 완료하고 따로 공유드리도록 하겠습니다.

**Comment by choding91** [comment]
사물인식 기능 구현 완료하였으며, 장고와 연동하여 문제 없는지 확인하는 단계로 넘어가겠습니다.

**Comment by choding91** [comment]
장고와 머신러닝 연동 중입니다.

**Comment by choding91** [comment]
코드 리팩토링 완료하였습니다.
